CONTIKI_PROYECT = rsi-p01-t01
all: $(CONTIKI_PROYECT)

CONTIKI = ../../../
CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

include $(CONTIKI)/Makefile.include

CONTIKIDIRS += ../aux
#CONTIKI_SOURCEFILES += aux.c

